Tests_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: |
      cat package.json
      cat package-lock.json
    populate_script: make install
  script: |
    if [[ -z $CODE_COVERAGE_RUN ]]; then
      make
    else
      make reportcoverage
    fi
  matrix:
    - container:
        image: node:latest
      matrix:
        - name: "Tests@Node:Latest"
        - name: "Deploy@Node:Latest"
          only_if: $CIRRUS_TAG != ""
          push_script: |
            touch ~/.npmrc
            echo "registry=https://registry.npmjs.com/" > ~/.npmrc
            echo "_auth=\"${NPMJS_PASS}\""
            echo "email=n8programs@gmail.com" > ~/.npmrc
            echo "always-auth=true" > ~/.npmrc
            make publish
          env:
            NPMJS_PASS: aDummyObject
        - name: "CodeCoverage@Node:Latest"
          env:
            CODE_COVERAGE_RUN: true
            CODECOV_TOKEN: ENCRYPTED[230fd82953b0b0ed3fbde809dbad5bc8cf92a3b88e03d5b86c5124e01a890a12fde06130fb35af71c19ec4485d4519e3]
          code_coverage_artifacts:
            path: ./coverage/**
    - container:
        image: node:dubnium
      name: "Tests@Node:Dubnium"
    - container:
        image: node:carbon
      name: "Tests@Node:Carbon"
