Tests_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: |
      cat package.json
      cat package-lock.json
    populate_script: npm i
  script: |
    if [[ -z $CODE_COVERAGE_RUN ]]; then
      npm test
    else
      npm run cov
    fi
  matrix:
    - container:
        image: node:latest
      matrix:
        - name: "Tests@Node:Latest"
        - name: "CodeCoverage@Node:Latest"
          env:
            CODE_COVERAGE_RUN: true
          code_coverage_artifacts:
            path: ./coverage/**
    - container:
        image: node:dubnium
      name: "Tests@Node:Dubnium"
    - container:
        image: node:carbon
      name: "Tests@Node:Carbon"
